name: petit
description: "An image compression application capable of compressing images in various formats, like HEIC, HEIF, PNG, and JPG, for efficient storage and faster file transfers without compromising quality"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.25+25

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

#  cupertino_icons: ^1.0.8
#
#  flutter_svg: ^2.0.11

  #Material You dynamic colours
  dynamic_color: ^1.8.1

  #Set app launcher icons
  icons_launcher: ^3.0.3

  #Service locator
  get_it: ^9.2.0

  #State management
  flutter_super: ^1.4.10

  #Image carousel slider
  carousel_slider: ^5.1.1

  #Image compression
  flutter_image_compress: ^2.4.0

  #Get image properties
  image_size_getter: ^2.4.1

  #Progress Indicator
  step_progress_indicator: ^1.0.2

  #For encoding and decoding
  image: ^4.5.4

  #For converting heic/heif to jpg/png
  heif_converter_plus: ^1.0.2

  #Image Picker
  image_picker: ^1.2.1

  #Gallery Saver
  gallery_saver_plus: ^3.2.9

  #For cancelable operation (To cancel a future)
  async: ^2.13.0

  #Firebase
  firebase_core: ^4.2.1

  #Firebase Crashlytics and others
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4

  #Pref
  shared_preferences: ^2.5.4

  #In app update - Android
  in_app_update: ^4.2.5

  #In app update - IOS and IOS but only used for IOS
  upgrader: ^12.3.0

  #Get temp cache directory
  path_provider: ^2.1.5

  # Video player
  video_player: ^2.10.1

  #Get video info
  ffmpeg_kit_flutter_new: ^4.1.0

  #Receive files by sharing
  share_handler: ^0.0.25

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

#  fonts:
#    - family: Satoshi
#      fonts:
#        - asset: assets/fonts/satoshi/Satoshi-Black.otf
#          weight: 900
#        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.otf
#          weight: 900
#        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
#          weight: 700
#        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
#          weight: 700
#        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
#          weight: 500
#        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
#          weight: 500
#        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
#          weight: 500
#        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
#          weight: 400
#        - asset: assets/fonts/satoshi/Satoshi-Light.otf
#          weight: 300
#        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
#          weight: 300

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
